language: node_js
dist: trusty
node_js:
        - "6"
addons:
        apt:
                packages:
                         - postgresql-contrib
                         - libssl-dev
                         - build-essential
services:
        - postgresql
        - redis
before_script:
         - createdb mold_development
         - createdb mold_test
         - psql -d mold_development -c 'create extension "uuid-ossp"'
         - psql -d mold_test -c 'create extension "uuid-ossp"'
         - npm install
         - npm install -g babel-cli gulp sequelize-cli mocha
         - npm test
