language: node_js
dist: trusty
node_js:
        - "6"
addons:
        apt:
                packages:
                         - postgresql-contrib
                         - libssl-dev
                         - build-essential
services:
        - postgresql
        - redis
before_script:
         - yarn install
         - yarn global add babel-cli gulp sequelize-cli mocha
         - gulp db:setup
         - gulp reset --db test
         - yarn test
